import React, { PureComponent } from 'react';

import Styled from './Welcome.styled.js';

class Welcome extends PureComponent {
  static defaultProps = {

  };

  static propTypes = {

  };

  render() {
    return (
      <Styled>
        <h1>H1 Title: Welcome</h1>
        <h2>H2 Title: a slightly smaller welcome</h2>
        <h3>H3 smallest title</h3>
        <h4>H4 first subtitle</h4>
        <h5>H5 second subtitle</h5>
        <h6>H6 last subtitle</h6>
        <br />
        <div>
          Egg whites, turkey sausage, wheat toast, water. Of course they don’t want us to eat our breakfast, so we are going to enjoy our breakfast. To be successful you’ve got to work hard, to make history, simple, you’ve got to make it. To be successful you’ve got to work hard, to make history, simple, you’ve got to make it. They key is to have every key, the key to open every door. Another one. They don’t want us to win. Always remember in the jungle there’s a lot of they in there, after you overcome they, you will make it to paradise.
          <span>
          <i>
            Text generated by Khaled Ipsum 🎩: <a href="http://khaledipsum.com/">Major Keys to Success</a>
          </i>
          </span>
        </div>
      </Styled>
    );
  }
}

export default Welcome;
